# Server configuration
server:
  port: 9090 #set your port
spring:
  application:
    name: JunityTest
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/junity_test_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  logging:
    pattern:
      console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
    file:
      name: app.log
    level:
      root: warn
      io:
        github:
          my-api: trace
      org:
        springframework:
          web: debug
          security: trace
  # trace
  # debug
  # info
  # warn
  # error
  springdoc:
    override-with-generic-response: false